-- Add AI enrichment columns to documents table
-- These columns store AI-generated metadata for better search experience

ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS ai_summary TEXT,
  ADD COLUMN IF NOT EXISTS ai_title TEXT,
  ADD COLUMN IF NOT EXISTS ai_tags TEXT[],
  ADD COLUMN IF NOT EXISTS content_type TEXT,
  ADD COLUMN IF NOT EXISTS last_enriched TIMESTAMPTZ;

-- Add index on content_type for potential filtering
CREATE INDEX IF NOT EXISTS idx_documents_content_type ON documents(content_type);

-- Add index on last_enriched for tracking enrichment status
CREATE INDEX IF NOT EXISTS idx_documents_last_enriched ON documents(last_enriched);

-- Add GIN index on ai_tags for efficient tag-based queries
CREATE INDEX IF NOT EXISTS idx_documents_ai_tags ON documents USING GIN(ai_tags);

-- Add comment to document the enrichment columns
COMMENT ON COLUMN documents.ai_summary IS 'AI-generated 2-3 sentence summary of the document content';
COMMENT ON COLUMN documents.ai_title IS 'Cleaned, human-friendly title (removes CMS artifacts)';
COMMENT ON COLUMN documents.ai_tags IS 'Array of searchable topic tags generated by AI';
COMMENT ON COLUMN documents.content_type IS 'Document category: faq, department, service, form, policy, guide, news, meeting, contact, calendar, other';
COMMENT ON COLUMN documents.last_enriched IS 'Timestamp of last AI enrichment run';
